package com.androidutillibrary.phonenumberiutil;

import java.util.ArrayList;
import java.util.List;

import in.androidUtil.library.phonenumberiutil.ParsedNumberData;

public class CountryList {

    private static final int DEFAULT_FLAG_RES = 1;

    public static List<ParsedNumberData> getLibraryMasterCountriesEnglish() {
        List<ParsedNumberData> countries = new ArrayList<>();
        countries.add(new ParsedNumberData("in", "91", "India", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ad", "376", "Andorra", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cn", "86", "China", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ae", "971", "United Arab Emirates (UAE)", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("af", "93", "Afghanistan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("us", "1", "United States", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ag", "1", "Antigua and Barbuda", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ai", "1", "Anguilla", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("al", "355", "Albania", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("am", "374", "Armenia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ao", "244", "Angola", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("aq", "672", "Antarctica", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ar", "54", "Argentina", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("as", "1", "American Samoa", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("at", "43", "Austria", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("au", "61", "Australia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("aw", "297", "Aruba", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ax", "358", "Åland Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("az", "994", "Azerbaijan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ba", "387", "Bosnia And Herzegovina", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bb", "1", "Barbados", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bd", "880", "Bangladesh", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("be", "32", "Belgium", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bf", "226", "Burkina Faso", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bg", "359", "Bulgaria", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bh", "973", "Bahrain", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bi", "257", "Burundi", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bj", "229", "Benin", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bl", "590", "Saint Barthélemy", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bm", "1", "Bermuda", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bn", "673", "Brunei Darussalam", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bo", "591", "Bolivia, Plurinational State Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("br", "55", "Brazil", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bs", "1", "Bahamas", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bt", "975", "Bhutan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bw", "267", "Botswana", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("by", "375", "Belarus", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("bz", "501", "Belize", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ca", "1", "Canada", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cc", "61", "Cocos (keeling) Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cd", "243", "Congo, The Democratic Republic Of The", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cf", "236", "Central African Republic", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cg", "242", "Congo", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ch", "41", "Switzerland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ci", "225", "Côte D'ivoire", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ck", "682", "Cook Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cl", "56", "Chile", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cm", "237", "Cameroon", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("co", "57", "Colombia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cr", "506", "Costa Rica", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cu", "53", "Cuba", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cv", "238", "Cape Verde", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cw", "599", "Curaçao", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cx", "61", "Christmas Island", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cy", "357", "Cyprus", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("cz", "420", "Czech Republic", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("de", "49", "Germany", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("dj", "253", "Djibouti", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("dk", "45", "Denmark", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("dm", "1", "Dominica", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("do", "1", "Dominican Republic", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("dz", "213", "Algeria", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ec", "593", "Ecuador", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ee", "372", "Estonia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("eg", "20", "Egypt", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("er", "291", "Eritrea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("es", "34", "Spain", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("et", "251", "Ethiopia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fi", "358", "Finland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fj", "679", "Fiji", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fk", "500", "Falkland Islands (malvinas)", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fm", "691", "Micronesia, Federated States Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fo", "298", "Faroe Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("fr", "33", "France", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ga", "241", "Gabon", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gb", "44", "United Kingdom", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gd", "1", "Grenada", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ge", "995", "Georgia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gf", "594", "French Guyana", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gh", "233", "Ghana", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gi", "350", "Gibraltar", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gl", "299", "Greenland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gm", "220", "Gambia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gn", "224", "Guinea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gp", "450", "Guadeloupe", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gq", "240", "Equatorial Guinea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gr", "30", "Greece", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gt", "502", "Guatemala", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gu", "1", "Guam", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gw", "245", "Guinea-bissau", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("gy", "592", "Guyana", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("hk", "852", "Hong Kong", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("hn", "504", "Honduras", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("hr", "385", "Croatia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ht", "509", "Haiti", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("hu", "36", "Hungary", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("id", "62", "Indonesia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ie", "353", "Ireland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("il", "972", "Israel", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("im", "44", "Isle Of Man", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("is", "354", "Iceland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("io", "246", "British Indian Ocean Territory", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("iq", "964", "Iraq", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ir", "98", "Iran, Islamic Republic Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("it", "39", "Italy", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("je", "44", "Jersey ", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("jm", "1", "Jamaica", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("jo", "962", "Jordan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("jp", "81", "Japan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ke", "254", "Kenya", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kg", "996", "Kyrgyzstan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kh", "855", "Cambodia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ki", "686", "Kiribati", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("km", "269", "Comoros", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kn", "1", "Saint Kitts and Nevis", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kp", "850", "North Korea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kr", "82", "South Korea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kw", "965", "Kuwait", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ky", "1", "Cayman Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("kz", "7", "Kazakhstan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("la", "856", "Lao People's Democratic Republic", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lb", "961", "Lebanon", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lc", "1", "Saint Lucia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("li", "423", "Liechtenstein", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lk", "94", "Sri Lanka", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lr", "231", "Liberia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ls", "266", "Lesotho", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lt", "370", "Lithuania", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lu", "352", "Luxembourg", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("lv", "371", "Latvia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ly", "218", "Libya", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ma", "212", "Morocco", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mc", "377", "Monaco", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("md", "373", "Moldova, Republic Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("me", "382", "Montenegro", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mf", "590", "Saint Martin", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mg", "261", "Madagascar", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mh", "692", "Marshall Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mk", "389", "Macedonia (FYROM)", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ml", "223", "Mali", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mm", "95", "Myanmar", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mn", "976", "Mongolia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mo", "853", "Macau", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mp", "1", "Northern Mariana Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mq", "596", "Martinique", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mr", "222", "Mauritania", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ms", "1", "Montserrat", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mt", "356", "Malta", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mu", "230", "Mauritius", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mv", "960", "Maldives", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mw", "265", "Malawi", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mx", "52", "Mexico", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("my", "60", "Malaysia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("mz", "258", "Mozambique", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("na", "264", "Namibia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nc", "687", "New Caledonia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ne", "227", "Niger", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nf", "672", "Norfolk Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ng", "234", "Nigeria", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ni", "505", "Nicaragua", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nl", "31", "Netherlands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("no", "47", "Norway", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("np", "977", "Nepal", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nr", "674", "Nauru", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nu", "683", "Niue", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("nz", "64", "New Zealand", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("om", "968", "Oman", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pa", "507", "Panama", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pe", "51", "Peru", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pf", "689", "French Polynesia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pg", "675", "Papua New Guinea", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ph", "63", "Philippines", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pk", "92", "Pakistan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pl", "48", "Poland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pm", "508", "Saint Pierre And Miquelon", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pn", "870", "Pitcairn Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pr", "1", "Puerto Rico", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ps", "970", "Palestine", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pt", "351", "Portugal", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("pw", "680", "Palau", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("py", "595", "Paraguay", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("qa", "974", "Qatar", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("re", "262", "Réunion", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ro", "40", "Romania", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("rs", "381", "Serbia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ru", "7", "Russian Federation", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("rw", "250", "Rwanda", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sa", "966", "Saudi Arabia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sb", "677", "Solomon Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sc", "248", "Seychelles", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sd", "249", "Sudan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("se", "46", "Sweden", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sg", "65", "Singapore", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sh", "290", "Saint Helena, Ascension And Tristan Da Cunha", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("si", "386", "Slovenia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sk", "421", "Slovakia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sl", "232", "Sierra Leone", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sm", "378", "San Marino", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sn", "221", "Senegal", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("so", "252", "Somalia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sr", "597", "Suriname", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ss", "211", "South Sudan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("st", "239", "Sao Tome And Principe", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sv", "503", "El Salvador", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sx", "1", "Sint Maarten", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sy", "963", "Syrian Arab Republic", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("sz", "268", "Swaziland", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tc", "1", "Turks and Caicos Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("td", "235", "Chad", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tg", "228", "Togo", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("th", "66", "Thailand", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tj", "992", "Tajikistan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tk", "690", "Tokelau", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tl", "670", "Timor-leste", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tm", "993", "Turkmenistan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tn", "216", "Tunisia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("to", "676", "Tonga", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tr", "90", "Turkey", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tt", "1", "Trinidad &amp; Tobago", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tv", "688", "Tuvalu", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tw", "886", "Taiwan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("tz", "255", "Tanzania, United Republic Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ua", "380", "Ukraine", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ug", "256", "Uganda", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("uy", "598", "Uruguay", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("uz", "998", "Uzbekistan", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("va", "379", "Holy See (vatican City State)", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("vc", "1", "Saint Vincent &amp; The Grenadines", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ve", "58", "Venezuela, Bolivarian Republic Of", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("vg", "1", "British Virgin Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("vi", "1", "US Virgin Islands", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("vn", "84", "Vietnam", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("vu", "678", "Vanuatu", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("wf", "681", "Wallis And Futuna", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ws", "685", "Samoa", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("xk", "383", "Kosovo", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("ye", "967", "Yemen", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("yt", "262", "Mayotte", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("za", "27", "South Africa", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("zm", "260", "Zambia", DEFAULT_FLAG_RES));
        countries.add(new ParsedNumberData("zw", "263", "Zimbabwe", DEFAULT_FLAG_RES));
        return countries;
    }


}
